# When the workspace is divided, there is no need of package and dependencies here

[workspace]
members = [
    "crates/backend_api",
    "crates/cli",
    "crates/data_normalization", 
    "crates/data_pipeline",
    "crates/logger",
    "crates/models",
    "crates/settings_loader",
]

resolver = "3"
