# When the workspace is divided, there is no need of package and dependencies here

[workspace]
members = [
    "crates/cli",
    "crates/data_pipeline",
    "crates/models",
    "crates/settings_loader",
    "crates/data/revolut", "crates/data/intesa_sanpaolo", "crates/data/interactive_brokers", "crates/data/china_construction_bank", "crates/data/avanza", "crates/data/alipay", "crates/data/skandinaviska_enskilda_banken", "crates/data/wechat", "crates/data/nordnet",
]

resolver = "3"
